#!/bin/bash
# Generated by generate-presets.py. Do not edit by hand.
GENERATED_MODEL_KEYS=gemma-4-26b-a4b,gemma-4-e2b,gemma-4-e4b,gemma-4-12b,gemma-4-31b,qwen-3.5-9b,qwen-3.6-35b-a3b-q4,qwen-3.6-35b-a3b,qwen-3.8-27b,ornith-1.5-9b-q4,ornith-1.5-9b-q6,ornith-1.5-9b-q8,ornith-1.5-35b-a3b-q4,ornith-1.5-35b-a3b-q8,nemotron-3.5-lightning-30b-a3b-q4,nemotron-3.5-lightning-30b-a3b-q8,muse-glimmer-30b-q4,muse-glimmer-30b-q6,glm-4.7-flash,deepseek-v4-flash,deepseek-v4-flash-0731,glm-5.2,glm-5.2-reap,smol
LEGACY_SMALL_MODELS=gemma-4-26b-a4b,gemma-4-e2b,gemma-4-e4b,qwen-3.6-35b-a3b,qwen-3.8-27b,glm-4.7-flash

model_key_fingerprint() {
  case "$1" in
    gemma-4-26b-a4b)
      printf '%s\n' 2def8e2819f818dd2f63e0343e5040146a65c672483177a40122e8a0f7e4b2bf
      ;;
    gemma-4-e2b)
      printf '%s\n' c53273b607b1bebcf5527b10e694b590a3f52b7b54f3dd917e3f94e0e2d1254f
      ;;
    gemma-4-e4b)
      printf '%s\n' b9758b8b8dfb9bf7dc62555abacf9a2444a2c2a1c215828fc6bb6104de9f2e85
      ;;
    gemma-4-12b)
      printf '%s\n' 60fa9b4137d028b0e824697e3ca724492307a80c7b191b687ab51eca72729b56
      ;;
    gemma-4-31b)
      printf '%s\n' 6ba538f39b09d5048123c7cf2d06717cfafdad74c19cd9f52cf78c36bad81e71
      ;;
    qwen-3.5-9b)
      printf '%s\n' 85d1ce4eec814b1d211fd1e580945faa1a44365b1e38d36ded6a89a9c9bc41dd
      ;;
    qwen-3.6-35b-a3b-q4)
      printf '%s\n' fd9d680cf1649eb631df3a86ddd44f7980a2f6c4a5471d5f96a12080567983cf
      ;;
    qwen-3.6-35b-a3b)
      printf '%s\n' 220a53029da9bdb364aa09b04649484bc13c9e3eb7ed6e0bfc023c527673bd53
      ;;
    qwen-3.8-27b)
      printf '%s\n' da4da442e7e218ac06d0b0d49500246c5971a21f4e201423a437cae67835893e
      ;;
    ornith-1.5-9b-q4)
      printf '%s\n' 1b71f0ed0dd61d649e9877c8e109ec01f6c41ac8067340785e6c7545622c4965
      ;;
    ornith-1.5-9b-q6)
      printf '%s\n' aefea607d9207ea5d7f194ce73ce89ea62b1a96283ff3e1904bc3c0dc2185a17
      ;;
    ornith-1.5-9b-q8)
      printf '%s\n' a7be280f9e550a775089aaf855df0bcbf2ed7bc9048db8ad668f09f04678ce91
      ;;
    ornith-1.5-35b-a3b-q4)
      printf '%s\n' 42fea226e906524bda371083c9297179d298238a5c456fa098f0c474b1bd7aec
      ;;
    ornith-1.5-35b-a3b-q8)
      printf '%s\n' 807d2603f3633ad872be62e3f57ea6843b85ff25210c9b2e5875e4954affb9f3
      ;;
    nemotron-3.5-lightning-30b-a3b-q4)
      printf '%s\n' dfa9e9d6f4c1a260fc733cb92aff98cf076d98bbd82053a5f32671e4577bc9ab
      ;;
    nemotron-3.5-lightning-30b-a3b-q8)
      printf '%s\n' cc28f5c22da934df8f826b2850fe10215cc1e3009f56b5edfe75ab34fd3b4ae0
      ;;
    muse-glimmer-30b-q4)
      printf '%s\n' 3487cfeb5fd04493ac69a13523eeafc42ddf2e0542f7d703abb3bac0ec1afc63
      ;;
    muse-glimmer-30b-q6)
      printf '%s\n' dbeb5cdc41dd03a83d8091c8babc678b8ad6edfb5ee026f8bc1d9833b17914d2
      ;;
    glm-4.7-flash)
      printf '%s\n' c8e2db8d593fbe6228799cff2d52d476c1f3303e43a557f5de1fa8bdd0610b3e
      ;;
    deepseek-v4-flash)
      printf '%s\n' e9db7f2356e4e4b16a414ed2d528b0b9b8732ecdbd8788af361fc98b973f4aba
      ;;
    deepseek-v4-flash-0731)
      printf '%s\n' b5a28890c23ff40fd3d48c7eaedb86e1a9dd3fefa16e244573f6e4b68407825b
      ;;
    glm-5.2)
      printf '%s\n' ba6b4d5d8b0fec075e5cb86086318c19c5f153a920fcc617c9b0b86ae9843e88
      ;;
    glm-5.2-reap)
      printf '%s\n' a256996375a232966ebabbbee1c5c835ec7261e3e1e0bf41bcf4ab9c4ce607dc
      ;;
    smol)
      printf '%s\n' ae59c9b29bfd1119440ca63fd0debd2d345e8454df12d19bd8ce68b323b41323
      ;;
    *)
      echo "[download-models] unknown model key: $1" >&2
      return 2
      ;;
  esac
}

model_key_artifacts() {
  case "$1" in
    gemma-4-26b-a4b)
      printf '%s\n' unsloth/gemma-4-26B-A4B-it-qat-GGUF/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
      printf '%s\n' unsloth/gemma-4-26B-A4B-it-qat-GGUF/mtp-gemma-4-26B-A4B-it.gguf
      printf '%s\n' unsloth/gemma-4-26B-A4B-it-qat-GGUF/mmproj-F16.gguf
      ;;
    gemma-4-e2b)
      printf '%s\n' unsloth/gemma-4-E2B-it-qat-GGUF/gemma-4-E2B-it-qat-UD-Q4_K_XL.gguf
      printf '%s\n' unsloth/gemma-4-E2B-it-qat-GGUF/mtp-gemma-4-E2B-it.gguf
      printf '%s\n' unsloth/gemma-4-E2B-it-qat-GGUF/mmproj-F16.gguf
      ;;
    gemma-4-e4b)
      printf '%s\n' unsloth/gemma-4-E4B-it-qat-GGUF/gemma-4-E4B-it-qat-UD-Q4_K_XL.gguf
      printf '%s\n' unsloth/gemma-4-E4B-it-qat-GGUF/mtp-gemma-4-E4B-it.gguf
      printf '%s\n' unsloth/gemma-4-E4B-it-qat-GGUF/mmproj-F16.gguf
      ;;
    gemma-4-12b)
      printf '%s\n' unsloth/gemma-4-12B-it-qat-GGUF/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
      printf '%s\n' unsloth/gemma-4-12B-it-qat-GGUF/MTP/mtp-gemma-4-12B-it-Q4_0.gguf
      printf '%s\n' unsloth/gemma-4-12B-it-qat-GGUF/mmproj-F16.gguf
      ;;
    gemma-4-31b)
      printf '%s\n' unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
      printf '%s\n' unsloth/gemma-4-31B-it-qat-GGUF/MTP/mtp-gemma-4-31B-it-Q4_0.gguf
      printf '%s\n' unsloth/gemma-4-31B-it-qat-GGUF/mmproj-F16.gguf
      ;;
    qwen-3.5-9b)
      printf '%s\n' unsloth/Qwen3.5-9B-GGUF/Qwen3.5-9B-UD-Q4_K_XL.gguf
      printf '%s\n' unsloth/Qwen3.5-9B-GGUF/mmproj-F16.gguf
      ;;
    qwen-3.6-35b-a3b-q4)
      printf '%s\n' unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
      ;;
    qwen-3.6-35b-a3b)
      printf '%s\n' unsloth/Qwen3.6-35B-A3B-MTP-GGUF/Qwen3.6-35B-A3B-UD-Q6_K_XL.gguf
      ;;
    qwen-3.8-27b)
      printf '%s\n' unsloth/Qwen3.8-27B-GGUF/Qwen3.8-27B-UD-Q6_K_XL.gguf
      ;;
    ornith-1.5-9b-q4)
      printf '%s\n' ornith-ai/Ornith-1.5-9B-GGUF/Ornith-1.5-9B-Q4_K_M.gguf
      printf '%s\n' ornith-ai/Ornith-1.5-9B-GGUF/mmproj-Ornith-1.5-9B-BF16.gguf
      ;;
    ornith-1.5-9b-q6)
      printf '%s\n' ornith-ai/Ornith-1.5-9B-GGUF/Ornith-1.5-9B-Q6_K.gguf
      printf '%s\n' ornith-ai/Ornith-1.5-9B-GGUF/mmproj-Ornith-1.5-9B-BF16.gguf
      ;;
    ornith-1.5-9b-q8)
      printf '%s\n' ornith-ai/Ornith-1.5-9B-GGUF/Ornith-1.5-9B-Q8_0.gguf
      printf '%s\n' ornith-ai/Ornith-1.5-9B-GGUF/mmproj-Ornith-1.5-9B-BF16.gguf
      ;;
    ornith-1.5-35b-a3b-q4)
      printf '%s\n' ornith-ai/Ornith-1.5-35B-A3B-GGUF/Ornith-1.5-35B-Q4_K_M.gguf
      printf '%s\n' ornith-ai/Ornith-1.5-35B-A3B-GGUF/mmproj-Ornith-1.5-35B-BF16.gguf
      ;;
    ornith-1.5-35b-a3b-q8)
      printf '%s\n' ornith-ai/Ornith-1.5-35B-A3B-GGUF/Ornith-1.5-35B-Q8_0.gguf
      printf '%s\n' ornith-ai/Ornith-1.5-35B-A3B-GGUF/mmproj-Ornith-1.5-35B-BF16.gguf
      ;;
    nemotron-3.5-lightning-30b-a3b-q4)
      printf '%s\n' ggml-org/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_0.gguf
      printf '%s\n' ggml-org/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF/mtp-NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_0.gguf
      ;;
    nemotron-3.5-lightning-30b-a3b-q8)
      printf '%s\n' ggml-org/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q8_0.gguf
      printf '%s\n' ggml-org/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF/mtp-NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q8_0.gguf
      ;;
    muse-glimmer-30b-q4)
      printf '%s\n' unsloth/Muse-Glimmer-30B-GGUF/Muse-Glimmer-30B-UD-Q4_K_XL.gguf
      printf '%s\n' unsloth/Muse-Glimmer-30B-GGUF/dflash-kquant.gguf
      printf '%s\n' unsloth/Muse-Glimmer-30B-GGUF/mmproj-kquant.gguf
      ;;
    muse-glimmer-30b-q6)
      printf '%s\n' unsloth/Muse-Glimmer-30B-GGUF/Muse-Glimmer-30B-UD-Q6_K_XL.gguf
      printf '%s\n' unsloth/Muse-Glimmer-30B-GGUF/dflash-kquant.gguf
      printf '%s\n' unsloth/Muse-Glimmer-30B-GGUF/mmproj-kquant.gguf
      ;;
    glm-4.7-flash)
      printf '%s\n' unsloth/GLM-4.7-Flash-REAP-23B-A3B-GGUF/GLM-4.7-Flash-REAP-23B-A3B-UD-Q6_K_XL.gguf
      ;;
    deepseek-v4-flash)
      printf '%s\n' antirez/deepseek-v4-gguf/DeepSeek-V4-Flash-Q4KExperts-F16HC-F16Compressor-F16Indexer-Q8Attn-Q8Shared-Q8Out-chat-v2-imatrix.gguf
      ;;
    deepseek-v4-flash-0731)
      printf '%s\n' unsloth/DeepSeek-V4-Flash-0731-GGUF/UD-Q4_K_XL/DeepSeek-V4-Flash-0731-UD-Q4_K_XL-00001-of-00005.gguf
      printf '%s\n' unsloth/DeepSeek-V4-Flash-0731-GGUF/UD-Q4_K_XL/DeepSeek-V4-Flash-0731-UD-Q4_K_XL-00002-of-00005.gguf
      printf '%s\n' unsloth/DeepSeek-V4-Flash-0731-GGUF/UD-Q4_K_XL/DeepSeek-V4-Flash-0731-UD-Q4_K_XL-00003-of-00005.gguf
      printf '%s\n' unsloth/DeepSeek-V4-Flash-0731-GGUF/UD-Q4_K_XL/DeepSeek-V4-Flash-0731-UD-Q4_K_XL-00004-of-00005.gguf
      printf '%s\n' unsloth/DeepSeek-V4-Flash-0731-GGUF/UD-Q4_K_XL/DeepSeek-V4-Flash-0731-UD-Q4_K_XL-00005-of-00005.gguf
      printf '%s\n' unsloth/DeepSeek-V4-Flash-0731-GGUF/dspark/dspark-DeepSeek-V4-Flash-0731-Q8_0.gguf
      ;;
    glm-5.2)
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00001-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00002-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00003-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00004-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00005-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00006-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00007-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00008-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00009-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00010-of-00011.gguf
      printf '%s\n' unsloth/GLM-5.2-GGUF/UD-Q4_K_XL/GLM-5.2-UD-Q4_K_XL-00011-of-00011.gguf
      ;;
    glm-5.2-reap)
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00001-of-00008.gguf
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00002-of-00008.gguf
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00003-of-00008.gguf
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00004-of-00008.gguf
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00005-of-00008.gguf
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00006-of-00008.gguf
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00007-of-00008.gguf
      printf '%s\n' 0xSero/GLM-5.2-REAP-504B-GGUF/GLM-5.2-REAP-504B-Q4_K_XL-00008-of-00008.gguf
      ;;
    smol)
      printf '%s\n' unsloth/SmolLM2-135M-Instruct-GGUF/SmolLM2-135M-Instruct-Q8_0.gguf
      ;;
    *)
      echo "[download-models] unknown model key: $1" >&2
      return 2
      ;;
  esac
}

download_model_key() {
  case "$1" in
    gemma-4-26b-a4b)
      download unsloth/gemma-4-26B-A4B-it-qat-GGUF '' --include '*UD-Q4_K_XL*' --include mtp-gemma-4-26B-A4B-it.gguf --include mmproj-F16.gguf
      ;;
    gemma-4-e2b)
      download unsloth/gemma-4-E2B-it-qat-GGUF '' --include '*UD-Q4_K_XL*' --include mtp-gemma-4-E2B-it.gguf --include mmproj-F16.gguf
      ;;
    gemma-4-e4b)
      download unsloth/gemma-4-E4B-it-qat-GGUF '' --include '*UD-Q4_K_XL*' --include mtp-gemma-4-E4B-it.gguf --include mmproj-F16.gguf
      ;;
    gemma-4-12b)
      download unsloth/gemma-4-12B-it-qat-GGUF 980b060c40a8539ac159e0501a3e0f66a6365af3 --include gemma-4-12B-it-qat-UD-Q4_K_XL.gguf --include MTP/mtp-gemma-4-12B-it-Q4_0.gguf --include mmproj-F16.gguf
      ;;
    gemma-4-31b)
      download unsloth/gemma-4-31B-it-qat-GGUF 43cc1aeb31adf47ec06a854507ce552cd9862e6f --include gemma-4-31B-it-qat-UD-Q4_K_XL.gguf --include MTP/mtp-gemma-4-31B-it-Q4_0.gguf --include mmproj-F16.gguf
      ;;
    qwen-3.5-9b)
      download unsloth/Qwen3.5-9B-GGUF 3885219b6810b007914f3a7950a8d1b469d598a5 --include Qwen3.5-9B-UD-Q4_K_XL.gguf --include mmproj-F16.gguf
      ;;
    qwen-3.6-35b-a3b-q4)
      download unsloth/Qwen3.6-35B-A3B-MTP-GGUF 5bc3e238d916f48a861bac2f8a1990a0e9b7e98d --include Qwen3.6-35B-A3B-UD-Q4_K_XL.gguf
      ;;
    qwen-3.6-35b-a3b)
      download unsloth/Qwen3.6-35B-A3B-MTP-GGUF '' --include '*UD-Q6_K_XL*'
      ;;
    qwen-3.8-27b)
      download unsloth/Qwen3.8-27B-GGUF 4604b899a826000505a834e623272db5b7fd62f6 --include Qwen3.8-27B-UD-Q6_K_XL.gguf
      ;;
    ornith-1.5-9b-q4)
      download ornith-ai/Ornith-1.5-9B-GGUF abdd624b12ebf020b767fff532ff44fe552b28c3 --include Ornith-1.5-9B-Q4_K_M.gguf --include mmproj-Ornith-1.5-9B-BF16.gguf
      ;;
    ornith-1.5-9b-q6)
      download ornith-ai/Ornith-1.5-9B-GGUF abdd624b12ebf020b767fff532ff44fe552b28c3 --include Ornith-1.5-9B-Q6_K.gguf --include mmproj-Ornith-1.5-9B-BF16.gguf
      ;;
    ornith-1.5-9b-q8)
      download ornith-ai/Ornith-1.5-9B-GGUF abdd624b12ebf020b767fff532ff44fe552b28c3 --include Ornith-1.5-9B-Q8_0.gguf --include mmproj-Ornith-1.5-9B-BF16.gguf
      ;;
    ornith-1.5-35b-a3b-q4)
      download ornith-ai/Ornith-1.5-35B-A3B-GGUF 12393612fd4f730ff5aadc23e9b8f9648aa49ceb --include Ornith-1.5-35B-Q4_K_M.gguf --include mmproj-Ornith-1.5-35B-BF16.gguf
      ;;
    ornith-1.5-35b-a3b-q8)
      download ornith-ai/Ornith-1.5-35B-A3B-GGUF 12393612fd4f730ff5aadc23e9b8f9648aa49ceb --include Ornith-1.5-35B-Q8_0.gguf --include mmproj-Ornith-1.5-35B-BF16.gguf
      ;;
    nemotron-3.5-lightning-30b-a3b-q4)
      download ggml-org/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF 9169f1a8ac58a29383ec27a447b4af3532da8864 --include NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_0.gguf --include mtp-NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_0.gguf
      ;;
    nemotron-3.5-lightning-30b-a3b-q8)
      download ggml-org/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF 9169f1a8ac58a29383ec27a447b4af3532da8864 --include NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q8_0.gguf --include mtp-NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q8_0.gguf
      ;;
    muse-glimmer-30b-q4)
      download unsloth/Muse-Glimmer-30B-GGUF faa5b025c584459c13febfa5c59883516710ae39 --include Muse-Glimmer-30B-UD-Q4_K_XL.gguf --include dflash-kquant.gguf --include mmproj-kquant.gguf
      ;;
    muse-glimmer-30b-q6)
      download unsloth/Muse-Glimmer-30B-GGUF faa5b025c584459c13febfa5c59883516710ae39 --include Muse-Glimmer-30B-UD-Q6_K_XL.gguf --include dflash-kquant.gguf --include mmproj-kquant.gguf
      ;;
    glm-4.7-flash)
      download unsloth/GLM-4.7-Flash-REAP-23B-A3B-GGUF '' --include '*UD-Q6_K_XL*'
      ;;
    deepseek-v4-flash)
      download antirez/deepseek-v4-gguf '' --include '*Q4KExperts-F16HC*imatrix*'
      ;;
    deepseek-v4-flash-0731)
      download unsloth/DeepSeek-V4-Flash-0731-GGUF 57326b941c4603e24d1a5e71c22520c66e086eb8 --include 'UD-Q4_K_XL/*' --include dspark/dspark-DeepSeek-V4-Flash-0731-Q8_0.gguf
      ;;
    glm-5.2)
      download unsloth/GLM-5.2-GGUF '' --include 'UD-Q4_K_XL/*'
      ;;
    glm-5.2-reap)
      download 0xSero/GLM-5.2-REAP-504B-GGUF '' --include '*Q4_K_XL*'
      ;;
    smol)
      download unsloth/SmolLM2-135M-Instruct-GGUF '' --include '*Q8_0.gguf'
      ;;
    *)
      echo "[download-models] unknown model key: $1" >&2
      return 2
      ;;
  esac
}
