#!/bin/bash
# Generated by generate-presets.py. Do not edit by hand.
GENERATED_MODEL_KEYS=gemma-4-26b-a4b,gemma-4-e2b,gemma-4-e4b,gemma-4-12b,gemma-4-31b,qwen-3.5-9b,qwen-3.6-35b-a3b,qwen-3.6-27b,glm-4.7-flash,deepseek-v4-flash,deepseek-v4-flash-0731,glm-5.2,glm-5.2-reap,smol
LEGACY_SMALL_MODELS=gemma-4-26b-a4b,gemma-4-e2b,gemma-4-e4b,qwen-3.6-35b-a3b,qwen-3.6-27b,glm-4.7-flash

download_model_key() {
  case "$1" in
    gemma-4-26b-a4b)
      download unsloth/gemma-4-26B-A4B-it-qat-GGUF '' --include '*UD-Q4_K_XL*' --include '*mtp-gemma*' --include mmproj-F16.gguf
      ;;
    gemma-4-e2b)
      download unsloth/gemma-4-E2B-it-qat-GGUF '' --include '*UD-Q4_K_XL*' --include '*mtp-gemma*' --include mmproj-F16.gguf
      ;;
    gemma-4-e4b)
      download unsloth/gemma-4-E4B-it-qat-GGUF '' --include '*UD-Q4_K_XL*' --include '*mtp-gemma*' --include mmproj-F16.gguf
      ;;
    gemma-4-12b)
      download unsloth/gemma-4-12B-it-qat-GGUF 980b060c40a8539ac159e0501a3e0f66a6365af3 --include gemma-4-12B-it-qat-UD-Q4_K_XL.gguf --include MTP/mtp-gemma-4-12B-it-Q4_0.gguf --include mmproj-F16.gguf
      ;;
    gemma-4-31b)
      download unsloth/gemma-4-31B-it-qat-GGUF 43cc1aeb31adf47ec06a854507ce552cd9862e6f --include gemma-4-31B-it-qat-UD-Q4_K_XL.gguf --include MTP/mtp-gemma-4-31B-it-Q4_0.gguf --include mmproj-F16.gguf
      ;;
    qwen-3.5-9b)
      download unsloth/Qwen3.5-9B-GGUF 3885219b6810b007914f3a7950a8d1b469d598a5 --include Qwen3.5-9B-UD-Q4_K_XL.gguf --include mmproj-F16.gguf
      ;;
    qwen-3.6-35b-a3b)
      download unsloth/Qwen3.6-35B-A3B-MTP-GGUF '' --include '*UD-Q6_K_XL*'
      ;;
    qwen-3.6-27b)
      download unsloth/Qwen3.6-27B-MTP-GGUF '' --include '*UD-Q6_K_XL*'
      ;;
    glm-4.7-flash)
      download unsloth/GLM-4.7-Flash-REAP-23B-A3B-GGUF '' --include '*UD-Q6_K_XL*'
      ;;
    deepseek-v4-flash)
      download antirez/deepseek-v4-gguf '' --include '*Q4KExperts-F16HC*imatrix*'
      ;;
    deepseek-v4-flash-0731)
      download unsloth/DeepSeek-V4-Flash-0731-GGUF 57326b941c4603e24d1a5e71c22520c66e086eb8 --include 'UD-Q4_K_XL/*' --include dspark/dspark-DeepSeek-V4-Flash-0731-Q8_0.gguf
      ;;
    glm-5.2)
      download unsloth/GLM-5.2-GGUF '' --include 'UD-Q4_K_XL/*'
      ;;
    glm-5.2-reap)
      download 0xSero/GLM-5.2-REAP-504B-GGUF '' --include '*Q4_K_XL*'
      ;;
    smol)
      download unsloth/SmolLM2-135M-Instruct-GGUF '' --include '*Q8_0.gguf'
      ;;
    *)
      echo "[download-models] unknown model key: $1" >&2
      return 2
      ;;
  esac
}
